# Generated by Django 2.2.5 on 2019-11-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name_plural': 'Colaboradores'},
        ),
    ]
