# Generated by Django 2.2.5 on 2019-11-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlasistencia',
            old_name='participantes',
            new_name='asistentes',
        ),
    ]
