# Generated by Django 2.2.5 on 2019-11-27 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_auto_20191127_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlasistencia',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
        ),
    ]
