# Generated by Django 2.2.5 on 2019-11-27 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0003_auto_20191126_1009'),
        ('material', '0004_auto_20191127_0831'),
        ('reportes', '0004_auto_20191127_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='actividad.Actividad')),
                ('materiales', models.ManyToManyField(blank=True, to='material.Material')),
            ],
        ),
    ]
