# Generated by Django 2.2.5 on 2019-11-27 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_controlmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlasistencia',
            options={'verbose_name_plural': 'Control de Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='controlmaterial',
            options={'verbose_name_plural': 'Control de Materiales'},
        ),
    ]
