# Generated by Django 2.2.5 on 2019-12-07 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_auto_20191127_0831'),
        ('inscripcion', '0005_remove_inscripcion_dia_hora_asistencia'),
        ('evento', '0011_remove_descuento_eventos'),
        ('reportes', '0006_auto_20191127_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlInscritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
            options={
                'verbose_name_plural': 'Control de Inscritos',
            },
        ),
        migrations.CreateModel(
            name='ControlCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
                ('ingresos', models.ManyToManyField(blank=True, to='caja.Ingreso')),
                ('salidas', models.ManyToManyField(blank=True, to='caja.Salida')),
            ],
            options={
                'verbose_name_plural': 'Control de Caja',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistentes', models.ManyToManyField(blank=True, to='inscripcion.Inscripcion')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evento.Evento')),
            ],
            options={
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
