# Generated by Django 2.2.5 on 2019-12-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0007_certificado_controlcaja_controlinscritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='asistentes',
        ),
    ]
