# Generated by Django 2.2.5 on 2019-12-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_remove_certificado_asistentes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcaja',
            name='ingresos',
        ),
        migrations.RemoveField(
            model_name='controlcaja',
            name='salidas',
        ),
    ]
