# Generated by Django 2.2.5 on 2019-11-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20191126_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
