# Generated by Django 2.2.5 on 2019-11-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_auto_20191127_0423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Materiales'},
        ),
    ]
