# Generated by Django 2.2.5 on 2019-11-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0002_auto_20191126_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='monto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
