# Generated by Django 2.2.5 on 2019-11-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripcion', '0004_inscripcion_dia_hora_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='dia_hora_asistencia',
        ),
    ]
