# Generated by Django 2.2.5 on 2019-11-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name_plural': 'Lugares'},
        ),
    ]
