# Generated by Django 2.2.5 on 2019-11-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20191126_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descuentos',
        ),
        migrations.AddField(
            model_name='evento',
            name='descuentos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.Descuento'),
        ),
    ]
