# Generated by Django 2.2.5 on 2019-11-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_auto_20191126_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descuentos',
        ),
        migrations.AddField(
            model_name='evento',
            name='descuentos',
            field=models.ManyToManyField(to='evento.Descuento'),
        ),
    ]
