# Generated by Django 2.2.5 on 2019-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_auto_20191126_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descuentos',
            field=models.ManyToManyField(related_name='eventos', to='evento.Descuento'),
        ),
    ]
