# Generated by Django 2.2.5 on 2019-11-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_auto_20191126_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventotipo',
            name='imagen',
        ),
    ]
