# Generated by Django 2.2.5 on 2019-11-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_auto_20191126_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='descuentos',
            field=models.ManyToManyField(blank=True, to='evento.Descuento'),
        ),
    ]
