# Generated by Django 2.2.5 on 2019-11-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0008_auto_20191127_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descuentos',
        ),
        migrations.AddField(
            model_name='descuento',
            name='eventos',
            field=models.ManyToManyField(blank=True, to='evento.Evento'),
        ),
    ]
