# Generated by Django 2.2.5 on 2019-11-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0009_auto_20191127_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='codigo',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
