# Generated by Django 2.2.5 on 2019-11-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0010_auto_20191127_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descuento',
            name='eventos',
        ),
    ]
