# Generated by Django 2.2.5 on 2019-11-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('hora', models.TimeField()),
                ('costo_inscripcion', models.FloatField()),
                ('num_incritos', models.IntegerField(blank=True, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lugar.Ambiente')),
            ],
        ),
    ]
