# Generated by Django 2.2.5 on 2019-11-14 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
        ),
    ]
