# Generated by Django 2.2.5 on 2019-11-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_actividad_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'Actividades'},
        ),
    ]
