# Generated by Django 2.2.5 on 2019-11-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0003_auto_20191126_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='num_incritos',
            new_name='num_inscritos',
        ),
    ]
