# Generated by Django 2.2.5 on 2019-11-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0004_auto_20191127_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='num_inscritos',
            field=models.IntegerField(default=0),
        ),
    ]
