# Generated by Django 2.2.5 on 2019-11-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0005_auto_20191127_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='num_inscritos',
        ),
    ]
