# Generated by Django 2.2.5 on 2019-11-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0006_remove_actividad_num_inscritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fecha',
            field=models.DateField(),
        ),
    ]
